"""LangGraph state definitions for Agentic Search."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


# ── Core Data Types ──────────────────────────────────────────────────


class JudgementVerdict(Enum):
    """5-way verdict from the Sufficient Context Agent.
    Inspired by AgentRAG's approach but formalized per the Google paper."""

    SUFFICIENT = "sufficient"               # All required facts covered → synthesize
    USEFUL_BUT_INCOMPLETE = "partial"        # Partial coverage → can attempt limited answer
    INSUFFICIENT = "insufficient"            # Missing key facts → need more search
    CONFLICTING = "conflicting"              # Evidence contradicts → need resolution search
    UNANSWERABLE = "unanswerable"            # No route, no evidence → abstain


class AnswerStatus(Enum):
    ANSWERED = "answered"
    PARTIAL = "partial"
    ABSTAINED = "abstained"


@dataclass
class RequiredFact:
    """A single fact needed to answer the question."""
    fact_id: str
    description: str                     # What to look for
    required_terms: list[str]            # Tokens that MUST appear in context
    conflict_terms: dict[str, list[str]] | None = None  # E.g., {"material": ["steel", "aluminum"]}


@dataclass
class SearchRoute:
    """One search direction: which corpus + what query."""
    corpus: str
    query: str
    rationale: str
    required_fact_ids: list[str]


@dataclass
class RetrievalPlan:
    """Full search plan — multiple routes for multi-hop questions."""
    question: str
    routes: list[SearchRoute]
    required_facts: list[RequiredFact]


@dataclass
class SubQuery:
    """A single query ready to send to a retriever."""
    query_id: str
    text: str
    target_corpus: str
    required_fact_ids: list[str]


@dataclass
class Snippet:
    """One chunk retrieved from a source."""
    snippet_id: str
    corpus: str
    document_id: str
    text: str
    score: float | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class FeedbackQuery:
    """A directed query generated by the Sufficient Context Agent to fill a gap."""
    query: str
    target_corpus: str
    reason: str
    related_fact_id: str


@dataclass
class ContextAssessment:
    """Output of the Sufficient Context Agent — the full judgment."""
    status: JudgementVerdict
    sufficiency_score: float              # 0..1 — fraction of required facts covered
    evidence_counts: dict[str, int]       # fact_id → snippet count
    unsupported_claims: list[str]         # Claims in draft that cite nothing
    missing_facts: list[str]              # fact_ids that were NOT found
    feedback_queries: list[FeedbackQuery]  # Directed queries for the next iteration
    reason: str                           # Human-readable judgment explanation
    draft_answer: str = ""                # Intermediate draft (for traceability)


@dataclass
class DraftAnswer:
    """Intermediate draft — before sufficiency check."""
    text: str
    claims: list[str]                     # Broken down claims
    citations: dict[str, list[str]]       # claim_index → [snippet_id]


@dataclass
class GroundedAnswer:
    """Final output with full traceability."""
    question: str
    answer: str | None
    status: AnswerStatus
    confidence: float                      # 0..1
    citations: dict[str, list[str]]       # claim → [snippet_id]
    iteration_count: int
    evidence_path: list[str]              # Human readable: "Fact X → Corpus Y → Doc Z"
    missing_info: str | None = None       # Only for PARTIAL / ABSTAINED


@dataclass
class IterationTrace:
    """Complete trace for one iteration for auditability."""
    iteration: int
    plan: RetrievalPlan
    subqueries: list[SubQuery]
    snippets: list[Snippet]
    draft: DraftAnswer | None
    assessment: ContextAssessment


# ── LangGraph State ──────────────────────────────────────────────────


@dataclass
class AgenticSearchState:
    """Full graph state — flows through all nodes."""
    # Input
    question: str
    corpora: dict[str, str]              # corpus_id → description
    max_iterations: int = 3
    search_config: dict[str, Any] = field(default_factory=dict)

    # Mutable across iterations
    plan: RetrievalPlan | None = None
    subqueries: list[SubQuery] = field(default_factory=list)
    snippets: dict[str, Snippet] = field(default_factory=dict)       # snippet_id → Snippet
    draft: DraftAnswer | None = None
    assessment: ContextAssessment | None = None
    iteration: int = 0
    dead_corpora: set[str] = field(default_factory=set)              # Exhausted corpora
    tried_queries: set[str] = field(default_factory=set)             # De-duplication
    traces: list[IterationTrace] = field(default_factory=list)
    search_stats: dict = field(default_factory=dict)                  # Mechanical search stats

    # Final output
    answer: GroundedAnswer | None = None

    def get_all_snippets(self) -> list[Snippet]:
        return list(self.snippets.values())

    def get_snippets_for_fact(self, fact_id: str) -> list[Snippet]:
        """Return snippets that match this required fact."""
        if not self.plan:
            return []
        fact = next((f for f in self.plan.required_facts if f.fact_id == fact_id), None)
        if not fact:
            return []
        terms = set(t.lower() for t in fact.required_terms)
        hits = []
        for sn in self.snippets.values():
            text_lower = sn.text.lower()
            if any(t in text_lower for t in terms):
                hits.append(sn)
        return hits
